repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^plugins/python/.*\.py$
      - id: ruff-format
        files: ^plugins/python/.*\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^plugins/python/(src|tests)/.*\.py$
        args: [--strict, --config-file=plugins/python/pyproject.toml]
        additional_dependencies: []
